// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQY6m6_F7Bkwf3ZxsTqQQdAGVlfCZbAYk',
    appId: '1:280406264657:web:6ec9abe11b7f32708e6170',
    messagingSenderId: '280406264657',
    projectId: 'chat-55125',
    authDomain: 'chat-55125.firebaseapp.com',
    storageBucket: 'chat-55125.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW3m6U100jGb46CG7duSzx3LiHicD9CLA',
    appId: '1:280406264657:android:656ea185cce8898f8e6170',
    messagingSenderId: '280406264657',
    projectId: 'chat-55125',
    storageBucket: 'chat-55125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASYs_nez8zVZ5EEy5EYNwmY7U-B5D8410',
    appId: '1:280406264657:ios:a7b39ed6a77dd46b8e6170',
    messagingSenderId: '280406264657',
    projectId: 'chat-55125',
    storageBucket: 'chat-55125.appspot.com',
    iosClientId: '280406264657-ju7n0uiqqdg6m6r9n3o2ldel5fo4mkac.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASYs_nez8zVZ5EEy5EYNwmY7U-B5D8410',
    appId: '1:280406264657:ios:a7b39ed6a77dd46b8e6170',
    messagingSenderId: '280406264657',
    projectId: 'chat-55125',
    storageBucket: 'chat-55125.appspot.com',
    iosClientId: '280406264657-ju7n0uiqqdg6m6r9n3o2ldel5fo4mkac.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
